### ISSUE TITLE
PHP 8.0.0 notice

### ISSUE THREAD

**Issue by oguilleux** [Sucuri/sucuri-wordpress-plugin#104]
Hello

I get this notice when switching to php 8 : 

Deprecated: Required parameter $old_user_data follows optional parameter $id in /wp-content/plugins/sucuri-scanner/src/hook.lib.php on line 999

Good luck

**Comment by imgerson** [comment]
Thanks for reporting this @oguilleux. I'll spin PHP 8 and give it a try. :)

**Comment by oguilleux** [comment]
It just seems to be the order of parameters in file /sucuri-scanner/src/hook.lib.php on line 999 :

It should NOT be 
`public static function hookProfileUpdate($id = 0, $old_user_data)`
but
`public static function hookProfileUpdate($old_user_data, $id = 0)`

**Comment by oguilleux** [comment]
@imgerson do you think you can fix this simple notice please ? It's been two month now.

**Comment by chrisblakley** [comment]
I started running into this deprecation notice as well anytime a plugin update became available. Instead of re-arranging the parameters, I added a default value of `false` to `$old_user_data` so that it would not require any additional changes throughout the plugin. Since there is a conditional that checks this parameter directly, the boolean default should work fine.

Hope this helps!

**Comment by imgerson** [comment]
@oguilleux @chrisblakley I allocated some time at the end of the week to keep working on PHP 8 related issues and PRs. I discovered that our reset plugin functionality is also affected on PHP 8, so I need to address that too.

@chrisblakley thanks for the PR 🎉
